# -*- coding: utf-8 -*-
"""aishwarya koppad 08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/17aishwaryak/a9d4a80617f79c6113cfee6ba9c418be/scratchpad.ipynb
"""

!pip install psycopg2

import pandas as pd
import numpy as np
import psycopg2
df = pd.read_csv('/content/Download Data - CRYPTOCURRENCY_US_COINDESK_BTCUSD.csv')
df.head()

df.describe()

df.describe()

df.describe()

df.nsmallest(5, 'High')

df.nlargest(10, 'Low')

df.query('open<close').head()